name: DriveBackupV2 Authenticator

on:
  push:
    paths:
      - 'Authenticator/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@master
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Deploy to Cloud Build
      run: |-
        gcloud builds submit \
          --quiet \
          --tag "gcr.io/${{ secrets.GCP_PROJECT_ID }}/authenticator:$GITHUB_SHA"
    
    - name: Deploy to Cloud Run
      uses: google-github-actions/deploy-cloudrun@main
      with:
        service: authenticator
        image: gcr.io/drivebackup-276620/authenticator
        credentials: ${{ secrets.GCP_SA_KEY }}