name: DriveBackupV2 Authenticator

on:
  workflow_dispatch:
  push:
    paths:
      - 'Authenticator/**'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Authenticator

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@master
      with:
        project_id: drivebackup-276620
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Deploy to Cloud Build
      run: |-
        gcloud builds submit \
          --quiet \
          --tag "gcr.io/drivebackup-276620/authenticator:$GITHUB_SHA"
    
    - name: Deploy to Cloud Run
      uses: google-github-actions/deploy-cloudrun@main
      with:
        service: authenticator
        image: gcr.io/drivebackup-276620/authenticator:${{ GITHUB_SHA }}
        credentials: ${{ secrets.GCP_SA_KEY }}